### ISSUE TITLE
Failure to access cleanroom.provider_subscriptions_vw from consumer side

### ISSUE THREAD

**Issue by drop-ben** [Snowflake-Labs/sfquickstart-data-clean-room#4]
I followed the [data clean room set up](https://quickstarts.snowflake.com/guide/build_a_data_clean_room_in_snowflake_advanced/?index=..%2F..index#4) and generated scripts for both provider and consumer via this [tool](https://snowflake-labs-sfquickstart-data-cle-dcr-setup-assistant-bkx7gg.streamlit.app/) but encountered issue when executing consumer_data.sql which is the 5th step setting up the consumer dataset. To be more specific, we could not run the following command due to a missing permission problem
```
// verify this simple query can NOT see providers data
select * from dcr_drop_test_script_app.cleanroom.provider_customers_vw;
// returns no rows but can see column names


-- Error: Object does not exist, or operation cannot be performed.
```

It seems the the row level policy dcr_drop_test_script_provider_db.shared_schema.data_firewall we set on the provider side blocks the selection on the consumer side. Could you help check what is missing on the consumer data setup?

**Comment by sfc-gh-bklein** [comment]
Sorry about that, this should be resolved now.  If you download new scripts from the tool, it should work.
